name: Python package

on: [workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        conda env create -f environment.yml
    - name: Test with pytest
      run: |
        conda activate album_storyteller
        pip install pytest pytest-cov
        python -m pytest test/unit
