name: Python package

on: push

jobs:
  test:
    defaults:
        run:
          shell: bash -l {0}
          
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: album_storyteller
        environment-file: environment.yml
        auto-activate-base: false
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        python -m pytest test/unit
